# Generated by Django 4.1.3 on 2022-11-04 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Содержание поручения")),
                ("date", models.DateField(verbose_name="Срок исполнения")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="В работе?"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Выполнено?"),
                ),
                (
                    "is_closed",
                    models.BooleanField(default=False, verbose_name="Закрыто?"),
                ),
                (
                    "chief",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chief_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Руководитель",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worker_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поручение",
                "verbose_name_plural": "Поручения",
            },
        ),
    ]
