#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

# Reload celery при изменении кода
watchmedo auto-restart --verbose --recursive --directory=./backend --pattern='*.py' \
-- celery --app=todos --workdir=./backend worker --loglevel=INFO

echo "Celery started successfully!"
