# Generated by Django 4.1.3 on 2022-11-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_usertodos_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertodos",
            name="email",
            field=models.EmailField(
                max_length=100, unique=True, verbose_name="Email адрес"
            ),
        ),
    ]
