# Generated by Django 4.1.3 on 2022-11-04 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_usertodos_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usertodos",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AddField(
            model_name="usertodos",
            name="chief",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Руководитель",
            ),
        ),
    ]
